//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advent {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InputData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InputData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advent.InputData", typeof(InputData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shrzvdcghblt21
        ///sixdddkcqjdnzzrgfourxjtwosevenhg9
        ///threevt1onegxgvc9flk
        ///7dmqzksnlcpbsqkzqlfour1four
        ///4seven9gdlnhqxfseven94five
        ///nldeightwoshgnsjnzmbkbxcxltsqtstrgdmvqvxbfour6six
        ///87mmlvfr4
        ///six1vvrlxx8two
        ///znmfvdlhvjtwo9three4tzjqcfcgnsevenccvnsjczlpm
        ///5sixninesixnh
        ///three1tbtwo
        ///five9seventwobqsjqzxkptkhsix1
        ///74fivemn
        ///sevenfivetsglnine8three
        ///spnvnfkbv4eightlmdkxmsfour574eight
        ///one4four2fivedcpqjmgc8
        ///two6sevensix33
        ///krc34five
        ///doneight64qgc251four7
        ///vpjthc6
        ///threethxbtffhbfourfive3
        ///onetwo5
        ///1sevenngjq [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day01 {
            get {
                return ResourceManager.GetString("Day01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day02 {
            get {
                return ResourceManager.GetString("Day02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day03 {
            get {
                return ResourceManager.GetString("Day03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day04 {
            get {
                return ResourceManager.GetString("Day04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day05 {
            get {
                return ResourceManager.GetString("Day05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day06 {
            get {
                return ResourceManager.GetString("Day06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day07 {
            get {
                return ResourceManager.GetString("Day07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day08 {
            get {
                return ResourceManager.GetString("Day08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day09 {
            get {
                return ResourceManager.GetString("Day09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day10 {
            get {
                return ResourceManager.GetString("Day10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day11 {
            get {
                return ResourceManager.GetString("Day11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day12 {
            get {
                return ResourceManager.GetString("Day12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day13 {
            get {
                return ResourceManager.GetString("Day13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day14 {
            get {
                return ResourceManager.GetString("Day14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day15 {
            get {
                return ResourceManager.GetString("Day15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day16 {
            get {
                return ResourceManager.GetString("Day16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day17 {
            get {
                return ResourceManager.GetString("Day17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day18 {
            get {
                return ResourceManager.GetString("Day18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day19 {
            get {
                return ResourceManager.GetString("Day19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day20 {
            get {
                return ResourceManager.GetString("Day20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day21 {
            get {
                return ResourceManager.GetString("Day21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day22 {
            get {
                return ResourceManager.GetString("Day22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day23 {
            get {
                return ResourceManager.GetString("Day23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day24 {
            get {
                return ResourceManager.GetString("Day24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day25 {
            get {
                return ResourceManager.GetString("Day25", resourceCulture);
            }
        }
    }
}
