//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advent {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InputData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InputData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advent.InputData", typeof(InputData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shrzvdcghblt21
        ///sixdddkcqjdnzzrgfourxjtwosevenhg9
        ///threevt1onegxgvc9flk
        ///7dmqzksnlcpbsqkzqlfour1four
        ///4seven9gdlnhqxfseven94five
        ///nldeightwoshgnsjnzmbkbxcxltsqtstrgdmvqvxbfour6six
        ///87mmlvfr4
        ///six1vvrlxx8two
        ///znmfvdlhvjtwo9three4tzjqcfcgnsevenccvnsjczlpm
        ///5sixninesixnh
        ///three1tbtwo
        ///five9seventwobqsjqzxkptkhsix1
        ///74fivemn
        ///sevenfivetsglnine8three
        ///spnvnfkbv4eightlmdkxmsfour574eight
        ///one4four2fivedcpqjmgc8
        ///two6sevensix33
        ///krc34five
        ///doneight64qgc251four7
        ///vpjthc6
        ///threethxbtffhbfourfive3
        ///onetwo5
        ///1sevenngjq [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day01 {
            get {
                return ResourceManager.GetString("Day01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game 1: 10 green, 9 blue, 1 red; 1 red, 7 green; 11 green, 6 blue; 8 blue, 12 green
        ///Game 2: 11 red, 7 green, 3 blue; 1 blue, 8 green, 5 red; 2 red, 12 green, 1 blue; 10 green, 5 blue, 7 red
        ///Game 3: 2 red, 7 green, 1 blue; 1 blue, 8 red; 7 green, 19 red, 5 blue; 1 blue, 10 green, 18 red; 10 red, 6 blue, 4 green
        ///Game 4: 2 blue, 5 green, 2 red; 7 red, 3 green; 3 blue, 2 red; 16 green, 2 blue
        ///Game 5: 1 blue, 9 red; 5 blue, 9 green, 6 red; 8 red, 10 blue, 3 green; 3 red, 13 green, 4 blue; 5 green, 9 red, 6 b [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day02 {
            get {
                return ResourceManager.GetString("Day02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .....................................164.................429.35...........221....................................................34.........
        ///........................464...........*.................................../.......53*.....954.763.....................114*.764..............
        ///223............275.....................725.....$.........460....176............................*............+.................&amp;.267.........
        ///.........854..........919.798...............541.....302...................723......$.. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day03 {
            get {
                return ResourceManager.GetString("Day03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card   1: 61 73 92 28 96 76 32 62 44 53 | 61 17 26 13 92  5 73 29 53 42 62 46 96 32 21 97 99 28 12  4  7 44 19 71 76
        ///Card   2:  3 88 36 12  2  9 15 55 21 89 | 23 39 98 36  2 24  9  3 78 95 55 37 12 61 38 88 85 89 13 15 96 45 21 25 30
        ///Card   3: 96 44 52 56 82 89 73 50  9 68 | 39 71 64 32 13 57 56 67 34 84 51 53 41 16 38 63  5 80 70 75  7 76 85 83 18
        ///Card   4: 54 84 76 44 38 33 12 17 93 94 | 18 21 53 11  7 98 78 92  9 32 29 50 86 23 95 77 22 79 71 80 60 35 54 36 91
        ///Card   5:  8 11 33 98 37 80 39 76 53 91  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day04 {
            get {
                return ResourceManager.GetString("Day04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seeds: 2637529854 223394899 3007537707 503983167 307349251 197383535 3543757609 276648400 2296792159 141010855 116452725 5160533 2246652813 49767336 762696372 160455077 3960442213 105867001 1197133308 38546766
        ///
        ///seed-to-soil map:
        ///1024364543 1121869540 764570177
        ///1788934720 0 30748436
        ///710359306 576061773 314005237
        ///1819683156 509305212 66756561
        ///478556776 890067010 231802530
        ///0 30748436 478556776
        ///
        ///soil-to-fertilizer map:
        ///3998185854 3762642503 103735883
        ///2968507762 2068943953 132922295
        ///1615660383 31282 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day05 {
            get {
                return ResourceManager.GetString("Day05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:        49     97     94     94
        ///Distance:   263   1532   1378   1851.
        /// </summary>
        public static string Day06 {
            get {
                return ResourceManager.GetString("Day06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32T3J 893
        ///A9942 54
        ///J57Q8 571
        ///779TK 931
        ///69696 457
        ///Q55Q5 478
        ///99399 735
        ///TA756 782
        ///QQQKQ 838
        ///QTJJA 995
        ///J7T7T 8
        ///22792 790
        ///588K8 376
        ///J77KT 191
        ///72T29 575
        ///58585 196
        ///58535 394
        ///263K5 566
        ///ATAAA 352
        ///7K7AK 477
        ///A3829 14
        ///22349 954
        ///KT647 244
        ///84848 208
        ///82A8A 77
        ///3A383 698
        ///97788 820
        ///QQ4Q7 991
        ///67Q66 837
        ///73QQ7 879
        ///Q4Q5Q 69
        ///Q5Q33 767
        ///585TT 52
        ///5K859 943
        ///238A3 170
        ///48887 668
        ///QAQQQ 591
        ///A8755 666
        ///4AK62 157
        ///4A9J4 350
        ///TJAAA 280
        ///AT9T9 592
        ///7Q497 390
        ///56748 681
        ///9425A 414
        ///5357J 737
        ///5QQQQ 597
        ///38 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day07 {
            get {
                return ResourceManager.GetString("Day07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LRRLRRRLLRRRLRRRLLRRLRRRLRRLRRLRLRLRLRLRLLRRRLRRLRLRRRLRRRLRLRRRLRLRRLRRRLRRRLRLLRRRLRLLLRLRRRLRLRRLRRLLLLRRLRRLRLRLRRLRLRRLRRRLRRRLRLRLRRLLLLRRLRLRRLLRRRLRLRLRLRRRLRLLLRLRLRRRLRLRRRLRRRLRRRLLRRLRRRLRRRLRRRLRRRLRLLRRRLRLRRRLRLRLRRRLRRLRRLLRRRLRRRLRRRLRLRLRLRRLRRRLRRLRLRLRLRRRR
        ///
        ///TJF = (TXF, NGK)
        ///PDL = (TXD, FRT)
        ///MVB = (HLF, BMQ)
        ///LKG = (JTG, THR)
        ///MPN = (CKC, FKR)
        ///HHN = (HFV, FGD)
        ///TMM = (GJG, CCJ)
        ///HJD = (PHB, FJM)
        ///JNC = (NMB, SND)
        ///HHR = (NBB, HMD)
        ///KCC = (BHB, PDC)
        ///CKN = (FRD, TQK)
        ///NCG = (VSC, PTD [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day08 {
            get {
                return ResourceManager.GetString("Day08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54
        ///12 27 47 68 92 149 343 943 2562 6504 15418 34500 73686 151710 303812 596709 1157888 2232401 4290657 8227316 15717112
        ///-1 12 52 135 290 585 1167 2315 4511 8546 15696 28027 48918 83927 142167 238407 396167 652136 1062308 1710303 2718418
        ///5 20 41 73 130 249 514 1092 2286 4613 8918 16538 29533 51004 85521 139687 222867 348114 533327 802679 1188356
        ///4 -1 -6 -11 -16 -21 -26 -31 -36 -41 -46 -51 -56 -61 -66 -71 -76 -81 -86 -91 -96
        ///17 19 24 49 132 341  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day09 {
            get {
                return ResourceManager.GetString("Day09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Day10 {
            get {
                return ResourceManager.GetString("Day10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Day11 {
            get {
                return ResourceManager.GetString("Day11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Day12 {
            get {
                return ResourceManager.GetString("Day12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Day13 {
            get {
                return ResourceManager.GetString("Day13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Day14 {
            get {
                return ResourceManager.GetString("Day14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Day15 {
            get {
                return ResourceManager.GetString("Day15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Day16 {
            get {
                return ResourceManager.GetString("Day16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Day17 {
            get {
                return ResourceManager.GetString("Day17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Day18 {
            get {
                return ResourceManager.GetString("Day18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Day19 {
            get {
                return ResourceManager.GetString("Day19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Day20 {
            get {
                return ResourceManager.GetString("Day20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Day21 {
            get {
                return ResourceManager.GetString("Day21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Day22 {
            get {
                return ResourceManager.GetString("Day22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Day23 {
            get {
                return ResourceManager.GetString("Day23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Day24 {
            get {
                return ResourceManager.GetString("Day24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Day25 {
            get {
                return ResourceManager.GetString("Day25", resourceCulture);
            }
        }
    }
}
